<a href="https://colab.research.google.com/github/Kashishkewat/python_practice/blob/main/day14_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Handling**

---



# Numpy

NumPy is a Python library used for:

1.Fast numerical calculations

2.Working with arrays & matrices

3.Scientific computing, ML, Data Science

**1. Install & Import**


In [2]:
#pip install numpy

In [3]:
import numpy as np

**2.Create numpy arrays form list**

In [4]:
a=[1,2,3,4]# one array
num=np.array(a)
print(num)

[1 2 3 4]


In [5]:
import numpy as np

zeros_array = np.zeros((2, 3))#np.zeros(): Creates an array filled with zeros.
ones_array = np.ones((3, 3))#np.ones(): Creates an array filled with ones.
constant_array = np.full((2, 2), 7)#np.full():create an array filled with speificed value
range_array = np.arange(0, 10, 2)  # start, stop, step np.arange(): Creates an array with values that are evenly spaced within a given range.

linspace_array = np.linspace(0, 1, 5)  # start, stop, num

print("Zero Array:","\n",zeros_array)
print("Ones Array:","\n",ones_array)
print("Constant Array:","\n",constant_array)
print("Range Array:","\n",range_array)
print("Linspace Array:","\n",linspace_array)

Zero Array: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Constant Array: 
 [[7 7]
 [7 7]]
Range Array: 
 [0 2 4 6 8]
Linspace Array: 
 [0.   0.25 0.5  0.75 1.  ]


In [6]:
import numpy as np

random_array = np.random.rand(2, 3)
normal_array = np.random.randn(2, 2)
randint_array = np.random.randint(1, 10, size=(2, 3))

print(random_array)
print(normal_array)
print(randint_array)

[[0.74519093 0.26737749 0.44513187]
 [0.91761339 0.52770779 0.98098151]]
[[-0.10468485 -1.67676389]
 [ 2.19562846 -0.53387059]]
[[7 6 6]
 [9 2 6]]


In [7]:
import numpy as np

identity_matrix = np.eye(3)
diagonal_array = np.diag([1, 2, 3])
zeros_like_array = np.zeros_like(diagonal_array)
ones_like_array = np.ones_like(diagonal_array)

print(identity_matrix)
print(diagonal_array)
print(zeros_like_array)
print(ones_like_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


**3. Accessing Elements in 1D Arrays**


In [8]:
a=np.array([1,2,3,4])
print(a[0])
print(a[1])
print(a[2])
print(a[3])

1
2
3
4


In [9]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[1, 2])

6


In [10]:
cube = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],

                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])

print(cube[1, 2, 0])

16


In [11]:
a=np.array([1,2,3,4,5])# Slicing Arrays

print(a[1:3])

[2 3]


In [12]:

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[0:2, :1])

[[1]
 [4]]


In [13]:
cube = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],

                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])

print(cube[:1, :2, 1:2])

[[[2]
  [5]]]


In [14]:
arr = np.array([10, 15, 20, 25, 30])# Boolean Indexing

print(arr[arr > 20])

[25 30]


In [15]:
arr = np.array([10, 15, 20, 25, 30])

print(arr[(arr > 10) & (arr < 30)])

[15 20 25]


In [16]:
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print(arr[indices])

[10 30 50]


In [17]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[[0, 2, 4]])

[1 3 5]


In [18]:
cube = np.random.rand(2, 2,2)# Ellipsis (...) in Indexing
print(cube[..., 1])

[[0.66429203 0.81561892]
 [0.44446853 0.49549105]]


In [19]:
arr = np.array([1, 2, 3,4,5,6,7,8])#Using np.newaxis to Add New Dimensions


print(arr[3:5, np.newaxis])

[[4]
 [5]]


In [20]:
arr=np.array([1,2,3,4,4,5,6,7])
arr[3:6]=55
print(arr)

[ 1  2  3 55 55 55  6  7]


**4.Reshapeing numpy array**

In [21]:
arr=np.array([1,2,3,4,5,6])# 2D-martix
r=arr.reshape(2,3)
print(r)

[[1 2 3]
 [4 5 6]]


In [22]:
arr=np.array([1,2,3,4,5,6,7,8,])
r=arr.reshape(2,2,2)
print(r)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
r = a.reshape(3,-1)
print(r)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**5.Resizing numpy array**

In [24]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((2, 3))
print(arr)

[[1 2 3]
 [4 5 6]]


In [25]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((3, 3))
print(arr)

[[1 2 3]
 [4 5 6]
 [0 0 0]]


In [26]:
arr = np.array([10, 20, 30, 40, 50])
arr.resize((2, 2))
print(arr)

[[10 20]
 [30 40]]


**6.numpy.stack() in python**

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
res = np.stack((a, b), axis=0)#axis=0: a and b become rows.

print(res)

[[1 2 3]
 [4 5 6]]


In [28]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
res = np.stack((a, b), axis=1)#axis=1: a and b become columns.

print(res)

[[1 4]
 [2 5]
 [3 6]]


In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
res = np.stack((a, b), axis=-1)#axis=-1: same as axis 1 because it refers to the last dimension.

print(res)

[[1 4]
 [2 5]
 [3 6]]


In [30]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])

y = np.array([[7, 8, 9],
              [10, 11, 12]])

print(np.stack((x, y), axis=0))
print(np.stack((x, y), axis=1))
print(np.stack((x, y), axis=2))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [31]:

m = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])

n = np.array([[[10, 20], [30, 40]],
              [[50, 60], [70, 80]]])

print(np.stack((m, n), axis=0))
print(np.stack((m, n), axis=1))
print(np.stack((m, n), axis=2))
print(np.stack((m, n), axis=3))

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[10 20]
   [30 40]]

  [[50 60]
   [70 80]]]]
[[[[ 1  2]
   [ 3  4]]

  [[10 20]
   [30 40]]]


 [[[ 5  6]
   [ 7  8]]

  [[50 60]
   [70 80]]]]
[[[[ 1  2]
   [10 20]]

  [[ 3  4]
   [30 40]]]


 [[[ 5  6]
   [50 60]]

  [[ 7  8]
   [70 80]]]]
[[[[ 1 10]
   [ 2 20]]

  [[ 3 30]
   [ 4 40]]]


 [[[ 5 50]
   [ 6 60]]

  [[ 7 70]
   [ 8 80]]]]


**7.Splitting Arrays in NumPy**


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6])
res = np.array_split(arr, 3)#allow uneven spliting
print(res)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [33]:
arr = np.arange(6)
res = np.split(arr, 2)#allow even spliting
print(res)

[array([0, 1, 2]), array([3, 4, 5])]


In [34]:
arr = np.arange(6)
res = np.split(arr, 2)
print(res)

[array([0, 1, 2]), array([3, 4, 5])]


In [35]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
res = np.vsplit(arr, 2)
print(res)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [36]:
arr = np.arange(24).reshape((2, 3, 4))
res = np.dsplit(arr, 2)
print(res)


[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]


#**NumPy** - **Arithmetic** **Operations**

---




In [37]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
res=np.add(a,b)
print(res)

[3 5 7 9]


In [38]:
res=np.subtract(b,a)
print(res)

[1 1 1 1]


In [39]:
res=np.multiply(a,b)
print(res)

[ 2  6 12 20]


In [40]:
res=np.divide(b,a)
print(res)

[2.         1.5        1.33333333 1.25      ]


In [41]:
res=np.mod(a,b)
print(res)

[1 2 3 4]


In [42]:
arr = np.array([5, 10, 15])
print(np.sum(arr))#np.sum(arr) adds all elements (5 + 10 + 15) and returns the total.



30


In [43]:
arr = [20, 2, 7, 1, 34]
res = np.mean(arr)
print(res)

12.8


In [44]:
a = 10
b = 21
print(np.maximum(a, b))
print(np.minimum(a, b))

21
10


**Matrix Operations in NumPy**


In [45]:

x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Addition:\n", np.add(x, y))
print("Subtraction:\n", np.subtract(x, y))
print("Division:\n", np.divide(x, y))

Addition:
 [[ 8 10]
 [13 15]]
Subtraction:
 [[-6 -6]
 [-5 -5]]
Division:
 [[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [46]:
print("Element-wise multiplication:\n", np.multiply(x, y))


Element-wise multiplication:
 [[ 7 16]
 [36 50]]


In [47]:
A = np.array([[1, 2],
              [3, 4]])

res = np.dot(A, A)    # Matrix multiplication
print(res)

[[ 7 10]
 [15 22]]


In [48]:
x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Square root:\n", np.sqrt(x))
print("Sum of all elements:", np.sum(y))

print("Column-wise sum:", np.sum(y, axis=0))
print("Row-wise sum:", np.sum(y, axis=1))
print("Transpose:\n", x.T)

Square root:
 [[1.         1.41421356]
 [2.         2.23606798]]
Sum of all elements: 34
Column-wise sum: [16 18]
Row-wise sum: [15 19]
Transpose:
 [[1 4]
 [2 5]]


**Products of Vectors and Matrices in NumPy**


In [49]:
import numpy as np

# Define vectors
a = np.array([2, 6])#For vectors a and b: (2 * 3) + (6 * 10) = 66

b = np.array([3, 10])

print("Inner product of vectors a and b =")
print(np.inner(a, b))

# Define matrices
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print("Inner product of matrices x and y =")
print(np.inner(x, y))

Inner product of vectors a and b =
66
Inner product of matrices x and y =
[[17 52]
 [13 62]]


In [50]:
# Define vectors
a = np.array([2, 6])
b = np.array([3, 10])

print("Outer product of vectors a and b =")#Example: First row: [2 * 3, 2 * 10] = [6, 10]
print(np.outer(a, b))

# Define matrices
x = np.array([[3, 6, 4], [9, 4, 6]])
y = np.array([[1, 15, 7], [3, 10, 8]])

print("Outer product of matrices x and y =")
print(np.outer(x, y))

Outer product of vectors a and b =
[[ 6 20]
 [18 60]]
Outer product of matrices x and y =
[[  3  45  21   9  30  24]
 [  6  90  42  18  60  48]
 [  4  60  28  12  40  32]
 [  9 135  63  27  90  72]
 [  4  60  28  12  40  32]
 [  6  90  42  18  60  48]]


In [51]:
# Define vectors as 3D (z=0 for 2D compatibility)
a = np.array([3, 6, 0])
b = np.array([9, 10, 0])

print("Cross product of vectors a and b =")
print(np.cross(a, b))

# Define matrices (already 3D rows)
x = np.array([[2, 6, 9], [2, 7, 3]])
y = np.array([[7, 5, 6], [3, 12, 3]])

print("Cross product of matrices x and y =")
print(np.cross(x, y))

Cross product of vectors a and b =
[  0   0 -24]
Cross product of matrices x and y =
[[ -9  51 -32]
 [-15   3   3]]


In [52]:
a = np.array([2, 3])
b = np.array([4, 5])
print(np.dot(a, b))

23


In [53]:
a = 2 + 3j
b = 4 + 5j
print(np.dot(a, b))

(-7+22j)


In [54]:
a = np.array([[1, 4],
              [5, 6]])

b = np.array([[2, 4],
              [5, 2]])

print(np.dot(a, b))

[[22 12]
 [40 32]]


In [55]:
a = np.array([[3, 5],
              [1, 2],
              [4, 1]])

b = np.array([2, 3])

print(np.dot(a, b))

[21  8 11]
